version: "3.8"

services:
  dora:
    image: ${DORA_IMAGE:-pk910/dora-the-explorer:latest}
    restart: unless-stopped
    command:
      - -config=/config/config.yaml
    ports:
      - ${HOST_IP:-}:${DORA_HOST_PORT:-3000}:3000
    depends_on:
      - execution
      - consensus
    volumes:
      - ${DORA_CONFIG_FILE:-./dora/config.yaml}:/config/config.yaml:ro
      - ${DORA_DATA_DIR:-./dora/data}:/data
    networks:
      default:
        aliases:
          - dora
