version: "3.8"

services:
  dora:
    image: pk910/dora-the-explorer:v1.17.0
    restart: unless-stopped
    command:
      - -config=/data/config.yaml
    ports:
      - 80:80
    volumes:
      - ./.explorer/dora:/data
    networks:
      default:
        aliases:
          - dora
