x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    image: ethereum/client-go:v1.11.6
    environment:
      - JWT_SECRET=${JWT_SECRET:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${EL_ARCHIVE_NODE:-}
      - MINIMAL_NODE=${EL_MINIMAL_NODE:-}
      - IPV6=${IPV6:-false}
      - ANCIENT_DIR=${ANCIENT_DIR:-}
      - CLIQUE_MINER=${CLIQUE_MINER:-}
      - CLIQUE_MINER_PASSWORD=${CLIQUE_MINER_PASSWORD:-}
      - CLIQUE_MINER_PRIVATE_KEY=${CLIQUE_MINER_PRIVATE_KEY:-}
      - CLIQUE_MINER_ADDRESS=${CLIQUE_MINER_ADDRESS:-}
      - EL_BOOTNODES=${EL_BOOTNODES:-}
    volumes:
      - ./geth/docker-entrypoint.sh:/entrypoint.sh
      - ./.eth/geth:/var/lib/geth
      - ./.eth/geth/${ANCIENT_DIR:-.nada}:/var/lib/ancient
      - ./.eth/etc/localtime:/etc/localtime:ro
      - ./.eth/ee-secret:/var/lib/geth/ee-secret
      - ./.eth/geth/genesis.json:/var/lib/geth/genesis.json
    ports:
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
          # This allows multiple Eth Docker stacks all connected to the same bridge network
          - ${EL_ALIAS:-default-execution}
    <<: *logging
    entrypoint:
      - /entrypoint.sh
      - geth
      - --datadir=/var/lib/geth
      - --networkid=${EL_NETWORK_ID:-84}
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.port=${EL_RPC_PORT:-8545}
      - --ws.addr=0.0.0.0
      - --ws.port=${EL_WS_PORT:-8546}
      - --ws.origins=*
      - --metrics
      - --authrpc.jwtsecret=/var/lib/geth/ee-secret/jwtsecret
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=${EE_PORT:-8551}
      - --authrpc.vhosts=*
      - --maxpeers=${EL_MAX_PEER_COUNT:-50}
      - --rpc.allow-unprotected-txs
      - --syncmode=full
    labels:
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060
      - metrics.instance=execution

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10001:10001"
    restart: "no"
    volumes:
      - geth-el-data:/var/lib/geth
    entrypoint: ["/bin/sh", "-c"]
    command: /bin/sh

networks:
  default:
    enable_ipv6: ${IPV6:-false}
