x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "unless-stopped"
    image: ${LH_IMAGE:-sigp/lighthouse:v7.0.1}
    pull_policy: if_not_present
    stop_grace_period: 1m
    volumes:
      - ./.eth/lighthouse/beacon:/var/lib/lighthouse/beacon
      - ./.eth/lighthouse/config:/var/lib/lighthouse/config
      - ./.eth/ee-secret:/var/lib/lighthouse/beacon/ee-secret
      - ./lighthouse/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - EL_NODE=${EL_NODE}
      - NODE_IP=${NODE_IP}
      - CL_BOOTNODE_ENR=${CL_BOOTNODE_ENR}
      - CL_GENESIS_STATE_URL=${CL_GENESIS_STATE_URL}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - CL_P2P_PORT=${CL_P2P_PORT:-9000}
      - NETWORK=${NETWORK}
    ports:
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
      - ${HOST_IP:-}:${CL_REST_PORT:-3500}:${CL_REST_PORT:-3500}/tcp
    networks:
      default:
        aliases:
          - eth2
          # This allows multiple Eth Docker stacks all connected to the same bridge network
          - ${CL_ALIAS:-default-consensus}
    <<: *logging
    entrypoint:
      - /docker-entrypoint.sh
      - lighthouse
      - beacon_node
      - --datadir=/var/lib/lighthouse/beacon
      - --http
      - --http-address=0.0.0.0
      - --http-port=3500
      - --http-allow-origin=*
      - --execution-endpoint=${EL_NODE}
      # - --debug-level=debug
      - --execution-jwt=/var/lib/lighthouse/beacon/ee-secret/jwtsecret
      - --testnet-dir=/var/lib/lighthouse/config
      - --disable-upnp
      - --enr-tcp-port=${CL_P2P_PORT:-9000}
      - --enr-udp-port=${CL_P2P_PORT:-9000}
      - --port=${CL_P2P_PORT:-9000}
      - --listen-address=0.0.0.0
      - --enr-address=${NODE_IP}
      # - --allow-insecure-genesis-sync
      # - --purge-db-force

  validator:
    restart: "unless-stopped"
    image: ${LH_IMAGE:-sigp/lighthouse:v7.0.1}
    pull_policy: if_not_present
    environment:
      - CL_NODE=${CL_NODE:-http://consensus:3500}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_BUILD_FACTOR=${MEV_BUILD_FACTOR}
      - MEV_NODE=${MEV_NODE}
      - DOPPELGANGER=${DOPPELGANGER}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
      - NETWORK=${NETWORK}
      - ENABLE_DIST_ATTESTATION_AGGR=${ENABLE_DIST_ATTESTATION_AGGR:-false}
    volumes:
      - ./.eth/lighthouse/config:/var/lib/lighthouse/config
      - ./.eth/lighthouse/validators:/var/lib/lighthouse/validators
      - ./lighthouse/docker-entrypoint-vc.sh:/docker-entrypoint-vc.sh:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        aliases:
          - ${VC_ALIAS:-vc}
    <<: *logging
    entrypoint:
      # - /bin/sh
      - /docker-entrypoint-vc.sh
      - lighthouse
      - validator_client
      - --beacon-nodes=${CL_NODE:-http://consensus:3500}
      - --validators-dir=/var/lib/lighthouse/validators
      - --testnet-dir=/var/lib/lighthouse/config
      - --http
      - --http-address=0.0.0.0
      - --unencrypted-http-transport
      - --http-port=5062
      - --http-allow-origin=*
      - --suggested-fee-recipient=0x23081455D3FEaf17426176dfc5Ee7A3ce519aD33
    depends_on:
      consensus:
        condition: service_started
      validator-import:
        condition: service_completed_successfully

  validator-import:
    restart: "no"
    image: ${LH_IMAGE:-sigp/lighthouse:v7.0.1}
    pull_policy: if_not_present
    volumes:
      - ./.eth/lighthouse/validator_keys:/var/lib/lighthouse/validator_keys
      - ./.eth/lighthouse/validators:/var/lib/lighthouse/validators
      - ./.eth/lighthouse/config:/var/lib/lighthouse/config
    <<: *logging
    environment:
      - NETWORK=${NETWORK}
      - CL_TESTNET_DIR=${CL_TESTNET_DIR:-/config}
    entrypoint:
      - lighthouse
      - account_manager
      - validator
      - import
      - --datadir=/var/lib/lighthouse
      - --directory=/var/lib/lighthouse/validator_keys
      - --password-file=/var/lib/lighthouse/validator_keys/password.txt
      - --testnet-dir=/var/lib/lighthouse/config
      - --reuse-password
  
  validator-exit:
    restart: "no"
    image: ${LH_IMAGE:-sigp/lighthouse:v7.0.1}
    pull_policy: if_not_present
    volumes:
      - ./.eth/lighthouse/validator_keys:/var/lib/lighthouse/validator_keys
      - ./.eth/lighthouse/validators:/var/lib/lighthouse/validators
      - ./.eth/lighthouse/config:/var/lib/lighthouse/config
    <<: *logging
    entrypoint:
      - lighthouse
      - account_manager
      - validator
      - exit
      - --datadir=/var/lib/lighthouse
      - --beacon-node=${CL_NODE:-http://consensus:3500}
      - --password-file=/var/lib/lighthouse/validator_keys/password.txt
      - --keystore=/var/lib/lighthouse/validator_keys

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    pull_policy: if_not_present
    # The API token has 640 permissions. Root copies it,
    # then switches to the local user's UID or if not provided,
    # 1000. The UID has to be able to write .eth/validator_keys
    # for the "keys delete" command.
    user: root
    volumes:
      - ${VALIDATOR_DATA_DIR:-./data/cl/validator}:/var/lib/lighthouse
      - ./.eth/validator_keys:/validator_keys
      - ./.eth/exit_messages:/exit_messages
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
      - WEB3SIGNER=${WEB3SIGNER:-false}
      - W3S_NODE=${W3S_NODE}
      - CL_NODE=${CL_NODE}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/lighthouse/validators/api-token.txt
      - ${VC_ALIAS:-vc}

  set-cl-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10002:10002"
    restart: "no"
    volumes:
      - lhconsensus-data:/var/lib/lighthouse
    entrypoint: ["/bin/sh", "-c"]
    command: /bin/sh

networks:
  default:
    enable_ipv6: ${IPV6:-false}
