version: "3.8"

services:
  bootnode:
    restart: unless-stopped
    image: ${LH_IMAGE:-sigp/lighthouse:v7.0.1}
    command:
      - lighthouse
      - boot_node
      - --datadir=/data
      - --testnet-dir=/config
      - --listen-address=${BOOTNODE_LISTEN_ADDRESS:-0.0.0.0}
      - --disable-packet-filter
      - --enable-enr-auto-update
      - --enr-address=${BOOTNODE_IP}
    volumes:
      - ${BOOTNODE_DATA_DIR:-./data/cl/bootnode}:/data
      - ${LH_CONFIG_DIR:-./config/lighthouse}:/config:ro
    networks:
      default:
        aliases:
          - bootnode
