version: "3.8"

services:
  bootnode:
    restart: unless-stopped
    image: ${LH_IMAGE:-sigp/lighthouse:v7.0.1}
    command:
      - lighthouse
      - boot_node
      - --datadir=/var/lib/lighthouse/bootnode
      - --testnet-dir=/var/lib/lighthouse/config
      - --listen-address=${BOOTNODE_LISTEN_ADDRESS:-0.0.0.0}
      - --disable-packet-filter
      - --enable-enr-auto-update
      - --enr-address=${NODE_IP}
    volumes:
      - ./.eth/lighthouse/bootnode:/var/lib/lighthouse/bootnode
      - ./.eth/lighthouse/config:/var/lib/lighthouse/config
    networks:
      default:
        aliases:
          - bootnode
