version: "3.8"

services:
  bootnode:
    restart: unless-stopped
    image: ${LH_IMAGE:-sigp/lighthouse:v7.0.1}
    ports:
      - ${HOST_IP:-}:${CL_BN_P2P_PORT:-9000}:${CL_BN_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}:${CL_BN_P2P_PORT:-9000}:${CL_BN_P2P_PORT:-9000}/udp
    command:
      - lighthouse
      - boot_node
      - --datadir=/var/lib/lighthouse/bootnode
      - --testnet-dir=/var/lib/lighthouse/config
      - --disable-packet-filter
      - --enable-enr-auto-update
      - --debug-level=trace
      - --listen-address=0.0.0.0
      - --enr-address=${NODE_IP}
    volumes:
      - ./.eth/lighthouse/bootnode:/var/lib/lighthouse/bootnode
      - ./.eth/lighthouse/config:/var/lib/lighthouse/config
    # networks:
    #   default:
    #     aliases:
    #       - bootnode
